spring.application.name=backend

cbs.base-url=${CBS_BASE_URL:http://localhost:9090/api/v1}
cbs.channel-id=${CBS_CHANNEL_ID:INTERNET_BANKING}
cbs.user-id=${CBS_USER_ID:APIUSER}
cbs.branch-code=${CBS_BRANCH_CODE:001}
